import type { CSSProperties } from 'react'

export const CLASSIC_WAVE_PAGE_WIDTH = 1120
export const CLASSIC_WAVE_PAGE_HEIGHT = 792

export const styles = {
  page: (primary: string, secondary: string): CSSProperties => ({
    width: CLASSIC_WAVE_PAGE_WIDTH,
    height: CLASSIC_WAVE_PAGE_HEIGHT,
    background: secondary || '#FAF8F5',
    color: '#24121A',
    border: '1px solid rgba(36,18,26,0.18)',
    borderRadius: 18,
    overflow: 'hidden',
    fontFamily: 'Inter, Arial, sans-serif',
    boxShadow: '0 22px 45px rgba(36, 18, 26, 0.14)',
    display: 'flex',
    flexDirection: 'column',
    ['--doc-primary' as string]: primary,
  }),
  stripWrap: (reverse: boolean): CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    height: 18,
    transform: reverse ? 'rotate(180deg)' : undefined,
  }),
  stripSegment: (color: string, clipPath: string): CSSProperties => ({ background: color, clipPath }),
  header: {
    display: 'grid',
    gridTemplateColumns: '210px 1fr 240px',
    alignItems: 'center',
    gap: 24,
    padding: '24px 46px 18px',
  } satisfies CSSProperties,
  brandBlock: { display: 'flex', flexDirection: 'column', gap: 6 } satisfies CSSProperties,
  logoBox: (primary: string): CSSProperties => ({
    width: 58,
    height: 58,
    borderRadius: 14,
    background: primary,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
  }),
  logoImage: { width: '100%', height: '100%', objectFit: 'cover', borderRadius: 14 } satisfies CSSProperties,
  logoText: { color: '#fff' } satisfies CSSProperties,
  logoPlaceholderText: {
    color: '#fff',
    display: 'block',
    fontSize: 9.5,
    fontWeight: 950,
    letterSpacing: '0.04em',
    lineHeight: 1.05,
    maxWidth: 46,
    overflowWrap: 'normal',
    textAlign: 'center',
    textTransform: 'uppercase',
  } satisfies CSSProperties,
  logoTagline: (accent: string): CSSProperties => ({
    margin: 0,
    fontSize: 8,
    color: accent,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  }),
  titleBlock: { textAlign: 'center', minWidth: 0 } satisfies CSSProperties,
  docTitle: { margin: 0, fontSize: 22, letterSpacing: '0.22em', textTransform: 'uppercase', fontWeight: 900 } satisfies CSSProperties,
  contactPills: {
    margin: '8px auto 0',
    minHeight: 24,
    width: '100%',
    maxWidth: 520,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '5px 9px',
    padding: 0,
  } satisfies CSSProperties,
  contactItem: { display: 'inline-flex', alignItems: 'center', gap: 7, fontSize: 12, color: '#24121A', fontWeight: 900, whiteSpace: 'nowrap' } satisfies CSSProperties,
  dot: (accent: string): CSSProperties => ({ width: 4, height: 4, borderRadius: 999, background: accent, display: 'inline-block' }),
  companyBlock: { textAlign: 'right' } satisfies CSSProperties,
  companyName: { margin: 0, fontSize: 14, fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  companyAddress: { margin: '6px 0 0', fontSize: 12, lineHeight: 1.45, color: '#24121A', fontWeight: 750 } satisfies CSSProperties,
  headerRule: (primary: string): CSSProperties => ({ height: 2, background: primary, opacity: 0.85, margin: '0 46px' }),
  metaBar: (primary: string): CSSProperties => ({
    margin: '14px 46px 0',
    padding: '10px 16px',
    borderRadius: 12,
    background: `${primary}14`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  }),
  metaPair: { margin: 0, display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: '#190A10', textTransform: 'uppercase', letterSpacing: '0.06em' } satisfies CSSProperties,
  contentArea: { flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', padding: '14px 46px 10px' } satisfies CSSProperties,
  body: { flex: '0 0 auto' } satisfies CSSProperties,
  invoiceGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 } satisfies CSSProperties,
  receiptGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 } satisfies CSSProperties,
  field: { border: '1px solid rgba(36,18,26,0.16)', background: 'rgba(255,255,255,0.62)', borderRadius: 12, padding: '9px 12px' } satisfies CSSProperties,
  invoiceDescriptionBlock: { gridColumn: '1 / -1', border: '1px solid rgba(36,18,26,0.16)', background: 'rgba(255,255,255,0.68)', borderRadius: 14, padding: '12px 14px', minHeight: 86 } satisfies CSSProperties,
  invoiceDescriptionValue: { display: 'block', color: '#0A0305', fontSize: 17, fontWeight: 950, lineHeight: 1.25 } satisfies CSSProperties,
  invoiceDescriptionDetails: { display: 'block', marginTop: 6, color: '#4D3B42', fontSize: 11.5, fontWeight: 750, lineHeight: 1.4 } satisfies CSSProperties,
  underlineField: {
    display: 'grid',
    gridTemplateColumns: '190px 1fr',
    alignItems: 'center',
    gap: 18,
    borderBottom: '1.2px solid rgba(36,18,26,0.2)',
    padding: '8px 0',
  } satisfies CSSProperties,
  fieldWide: { gridColumn: '1 / -1' } satisfies CSSProperties,
  fieldLabel: { display: 'block', marginBottom: 4, fontSize: 10.5, fontWeight: 950, color: '#24121A', textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  fieldValue: { display: 'block', fontSize: 15.5, lineHeight: 1.28, color: '#0A0305', fontWeight: 950 } satisfies CSSProperties,
  tableWrap: { gridColumn: '1 / -1', border: '1px solid rgba(36,18,26,0.16)', borderRadius: 14, overflow: 'hidden', background: 'rgba(255,255,255,0.68)' } satisfies CSSProperties,
  tableHead: (accent: string): CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '1fr 80px 130px 130px',
    gap: 0,
    background: accent,
    color: '#0E0508',
    fontSize: 10.5,
    fontWeight: 950,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    padding: '8px 14px',
  }),
  tableRow: { display: 'grid', gridTemplateColumns: '1fr 80px 130px 130px', padding: '8px 14px', borderTop: '1px solid rgba(36,18,26,0.16)', fontSize: 13.5, color: '#0A0305', fontWeight: 850, alignItems: 'center' } satisfies CSSProperties,
  tableDescription: { display: 'grid', gap: 2 } satisfies CSSProperties,
  tableDetails: { display: 'block', color: '#5C4B51', fontSize: 10.5, lineHeight: 1.25, fontWeight: 750 } satisfies CSSProperties,
  tableEmptyRow: { display: 'grid', gridTemplateColumns: '1fr 80px 130px 130px', minHeight: 22, borderTop: '1px solid rgba(36,18,26,0.08)', alignItems: 'center' } satisfies CSSProperties,
  totalsBox: (accent: string): CSSProperties => ({ gridColumn: '1 / -1', justifySelf: 'end', width: 330, borderRadius: 14, overflow: 'hidden', border: '1px solid rgba(36,18,26,0.12)', background: `${accent}18` }),
  totalLine: (strong: boolean): CSSProperties => ({ display: 'flex', justifyContent: 'space-between', padding: strong ? '10px 13px' : '8px 13px', fontSize: strong ? 11 : 9, fontWeight: strong ? 900 : 700, color: strong ? '#7B1E37' : '#342129', borderTop: strong ? '1px solid rgba(36,18,26,0.12)' : undefined }),
  receiptTotalsGrid: { gridColumn: '1 / -1', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 28, marginTop: 12 } satisfies CSSProperties,
  receiptTotalBox: (index: number, accent: string): CSSProperties => {
    const colors = [
      { border: '#315B7C', color: '#18344C', bg: 'rgba(49,91,124,0.05)' },
      { border: '#329A66', color: '#278457', bg: 'rgba(50,154,102,0.08)' },
      { border: '#B33A4E', color: '#9B1E37', bg: 'rgba(179,58,78,0.08)' },
    ][index] ?? { border: accent, color: '#24121A', bg: 'rgba(255,255,255,0.4)' }

    return {
      border: `2px solid ${colors.border}`,
      borderRadius: 6,
      background: colors.bg,
      color: colors.color,
      minHeight: 44,
      padding: '6px 10px',
      textAlign: 'center',
    }
  },
  receiptTotalLabel: { display: 'block', marginBottom: 5, fontSize: 10.5, fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.06em', textAlign: 'left' } satisfies CSSProperties,
  receiptTotalValue: { display: 'block', fontSize: 20, fontWeight: 950, lineHeight: 1.05 } satisfies CSSProperties,
  signatureSection: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 82, marginTop: 'auto', padding: '20px 38px 0', alignItems: 'end' } satisfies CSSProperties,
  invoiceSignatureSection: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 82, marginTop: 'auto', padding: '20px 38px 0', alignItems: 'end' } satisfies CSSProperties,
  signatureBlock: { textAlign: 'center' } satisfies CSSProperties,
  signatureSpace: { height: 42, display: 'flex', alignItems: 'end', justifyContent: 'center' } satisfies CSSProperties,
  signatureImage: { maxWidth: 138, maxHeight: 40, objectFit: 'contain', filter: 'contrast(1.12) saturate(1.08)' } satisfies CSSProperties,
  signatureLine: (primary: string): CSSProperties => ({ height: 1.6, background: primary, opacity: 1 }),
  signatureLabel: { margin: '6px 0 0', fontSize: 10.5, color: '#0A0305', fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  footer: (primary: string): CSSProperties => ({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 46px', background: `${primary}12`, fontSize: 10.5, color: '#24121A', fontWeight: 850 }),
}
