import type { CSSProperties } from 'react'

export const CLASSIC_WAVE_PAGE_WIDTH = 1120
export const CLASSIC_WAVE_PAGE_HEIGHT = 792

export const styles = {
  page: (primary: string, secondary: string): CSSProperties => ({
    width: CLASSIC_WAVE_PAGE_WIDTH,
    height: CLASSIC_WAVE_PAGE_HEIGHT,
    background: secondary || '#FAF8F5',
    color: '#24121A',
    border: '1px solid rgba(36,18,26,0.18)',
    borderRadius: 18,
    overflow: 'hidden',
    fontFamily: 'Inter, Arial, sans-serif',
    boxShadow: '0 22px 45px rgba(36, 18, 26, 0.14)',
    display: 'flex',
    flexDirection: 'column',
    ['--doc-primary' as string]: primary,
  }),
  stripWrap: (reverse: boolean): CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    height: 18,
    transform: reverse ? 'rotate(180deg)' : undefined,
  }),
  stripSegment: (color: string, clipPath: string): CSSProperties => ({ background: color, clipPath }),
  header: {
    display: 'grid',
    gridTemplateColumns: '210px 1fr 240px',
    alignItems: 'center',
    gap: 24,
    padding: '24px 46px 18px',
  } satisfies CSSProperties,
  brandBlock: { display: 'flex', flexDirection: 'column', gap: 6 } satisfies CSSProperties,
  logoBox: (primary: string): CSSProperties => ({
    width: 58,
    height: 58,
    borderRadius: 14,
    background: primary,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
  }),
  logoImage: { width: '100%', height: '100%', objectFit: 'cover', borderRadius: 14 } satisfies CSSProperties,
  logoText: { color: '#fff' } satisfies CSSProperties,
  logoTagline: (accent: string): CSSProperties => ({
    margin: 0,
    fontSize: 8,
    color: accent,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  }),
  titleBlock: { textAlign: 'center', minWidth: 0 } satisfies CSSProperties,
  docTitle: { margin: 0, fontSize: 22, letterSpacing: '0.22em', textTransform: 'uppercase', fontWeight: 900 } satisfies CSSProperties,
  contactPills: { marginTop: 8, display: 'flex', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', gap: '4px 7px' } satisfies CSSProperties,
  contactItem: { display: 'inline-flex', alignItems: 'center', gap: 7, fontSize: 11, color: '#24121A', fontWeight: 800, whiteSpace: 'nowrap' } satisfies CSSProperties,
  dot: (accent: string): CSSProperties => ({ width: 4, height: 4, borderRadius: 999, background: accent, display: 'inline-block' }),
  companyBlock: { textAlign: 'right' } satisfies CSSProperties,
  companyName: { margin: 0, fontSize: 14, fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  companyAddress: { margin: '6px 0 0', fontSize: 12, lineHeight: 1.45, color: '#24121A', fontWeight: 750 } satisfies CSSProperties,
  headerRule: (primary: string): CSSProperties => ({ height: 2, background: primary, opacity: 0.85, margin: '0 46px' }),
  metaBar: (primary: string): CSSProperties => ({
    margin: '14px 46px 0',
    padding: '10px 16px',
    borderRadius: 12,
    background: `${primary}14`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  }),
  metaPair: { margin: 0, display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: '#190A10', textTransform: 'uppercase', letterSpacing: '0.06em' } satisfies CSSProperties,
  body: { flex: '0 0 auto', padding: '14px 46px 4px' } satisfies CSSProperties,
  invoiceGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 } satisfies CSSProperties,
  receiptGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 } satisfies CSSProperties,
  field: { border: '1px solid rgba(36,18,26,0.12)', background: 'rgba(255,255,255,0.42)', borderRadius: 12, padding: '10px 12px' } satisfies CSSProperties,
  underlineField: {
    display: 'grid',
    gridTemplateColumns: '190px 1fr',
    alignItems: 'center',
    gap: 18,
    borderBottom: '1px solid rgba(36,18,26,0.13)',
    padding: '9px 0',
  } satisfies CSSProperties,
  fieldWide: { gridColumn: '1 / -1' } satisfies CSSProperties,
  fieldLabel: { display: 'block', marginBottom: 5, fontSize: 10.5, fontWeight: 950, color: '#24121A', textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  fieldValue: { display: 'block', fontSize: 15, lineHeight: 1.35, color: '#0E0508', fontWeight: 900 } satisfies CSSProperties,
  tableWrap: { gridColumn: '1 / -1', border: '1px solid rgba(36,18,26,0.13)', borderRadius: 14, overflow: 'hidden', background: 'rgba(255,255,255,0.5)' } satisfies CSSProperties,
  tableHead: (accent: string): CSSProperties => ({
    display: 'grid',
    gridTemplateColumns: '1fr 80px 130px 130px',
    gap: 0,
    background: accent,
    color: '#0E0508',
    fontSize: 10.5,
    fontWeight: 950,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    padding: '9px 14px',
  }),
  tableRow: { display: 'grid', gridTemplateColumns: '1fr 80px 130px 130px', padding: '9px 14px', borderTop: '1px solid rgba(36,18,26,0.16)', fontSize: 13, color: '#0E0508', fontWeight: 800, alignItems: 'center' } satisfies CSSProperties,
  tableEmptyRow: { display: 'grid', gridTemplateColumns: '1fr 80px 130px 130px', minHeight: 30, borderTop: '1px solid rgba(36,18,26,0.08)', alignItems: 'center' } satisfies CSSProperties,
  totalsBox: (accent: string): CSSProperties => ({ gridColumn: '1 / -1', justifySelf: 'end', width: 330, borderRadius: 14, overflow: 'hidden', border: '1px solid rgba(36,18,26,0.12)', background: `${accent}18` }),
  totalLine: (strong: boolean): CSSProperties => ({ display: 'flex', justifyContent: 'space-between', padding: strong ? '10px 13px' : '8px 13px', fontSize: strong ? 11 : 9, fontWeight: strong ? 900 : 700, color: strong ? '#7B1E37' : '#342129', borderTop: strong ? '1px solid rgba(36,18,26,0.12)' : undefined }),
  receiptTotalsGrid: { gridColumn: '1 / -1', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 32, marginTop: 10 } satisfies CSSProperties,
  receiptTotalBox: (index: number, accent: string): CSSProperties => {
    const colors = [
      { border: '#315B7C', color: '#18344C', bg: 'rgba(49,91,124,0.05)' },
      { border: '#329A66', color: '#278457', bg: 'rgba(50,154,102,0.08)' },
      { border: '#B33A4E', color: '#9B1E37', bg: 'rgba(179,58,78,0.08)' },
    ][index] ?? { border: accent, color: '#24121A', bg: 'rgba(255,255,255,0.4)' }

    return {
      border: `2px solid ${colors.border}`,
      borderRadius: 6,
      background: colors.bg,
      color: colors.color,
      minHeight: 42,
      padding: '6px 10px',
      textAlign: 'center',
    }
  },
  receiptTotalLabel: { display: 'block', marginBottom: 5, fontSize: 10.5, fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.06em', textAlign: 'left' } satisfies CSSProperties,
  receiptTotalValue: { display: 'block', fontSize: 20, fontWeight: 950, lineHeight: 1.05 } satisfies CSSProperties,
  signatureSection: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 82, marginTop: 42, padding: '0 84px 10px', alignItems: 'end' } satisfies CSSProperties,
  invoiceSignatureSection: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 82, marginTop: 46, padding: '0 84px 12px', alignItems: 'end' } satisfies CSSProperties,
  signatureBlock: { textAlign: 'center' } satisfies CSSProperties,
  signatureSpace: { height: 48, display: 'flex', alignItems: 'end', justifyContent: 'center' } satisfies CSSProperties,
  signatureImage: { maxWidth: 130, maxHeight: 38, objectFit: 'contain' } satisfies CSSProperties,
  signatureLine: (primary: string): CSSProperties => ({ height: 1.5, background: primary, opacity: 0.9 }),
  signatureLabel: { margin: '6px 0 0', fontSize: 10, color: '#190A10', fontWeight: 900, textTransform: 'uppercase', letterSpacing: '0.08em' } satisfies CSSProperties,
  footer: (primary: string): CSSProperties => ({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 46px', background: `${primary}12`, fontSize: 8, fontStyle: 'italic', color: '#6F5C64' }),
}
