import type { StepDeadlineReviewProps } from '../stepDeadlineReview.types'

export type ReviewSummaryProps = Pick<
  StepDeadlineReviewProps,
  | 'amendmentArea'
  | 'amendmentDescription'
  | 'amendmentIssueType'
  | 'amendmentTarget'
  | 'charge'
  | 'clientName'
  | 'clientPhone'
  | 'deadlineDate'
  | 'deadlineTime'
  | 'deposit'
  | 'detailsOpen'
  | 'effectiveItemType'
  | 'expenses'
  | 'isAmendmentMode'
  | 'makeCategory'
  | 'materialColor'
  | 'materialQuality'
  | 'materialSource'
  | 'materialYards'
  | 'nonBodyDescription'
  | 'orderMode'
  | 'persons'
  | 'projectedProfit'
  | 'referencePhotoNames'
  | 'sameItemForAll'
  | 'scopeLabel'
  | 'selectedMaterialValue'
  | 'selectedNonBodyFields'
  | 'totalExpenses'
  | 'onDetailsOpenChange'
>
