export const queryKeys = {
  profile: ['profile'] as const,
  settings: ['settings'] as const,
  clients: ['clients'] as const,
  client: (id: string) => ['client', id] as const,
  jobs: (status?: string) => ['jobs', status ?? 'all'] as const,
  clientJobs: (clientId: string) => ['client-jobs', clientId] as const,
  job: (id: string) => ['job', id] as const,
  jobExpenses: (jobId: string) => ['job-expenses', jobId] as const,
  jobPersons: (jobId: string) => ['job-persons', jobId] as const,
  dashboardMonthly: (monthCount = 6) => ['dashboard', 'monthly', monthCount] as const,
  dashboardStatus: (monthKey?: string) => ['dashboard', 'status', monthKey ?? 'all'] as const,
  recentJobs: (limit = 5) => ['dashboard', 'recent-jobs', limit] as const,
  notifications: ['notifications'] as const,
  supportTickets: ['support-tickets'] as const,
  supportCooldown: ['support-tickets', 'cooldown'] as const,
  subscription: ['subscription'] as const,
  feature: (featureKey: string) => ['feature-access', featureKey] as const,
  documents: (jobId: string) => ['documents', jobId] as const,
}
