import { Link } from 'react-router-dom'
import HistoryBackButton from '../components/shared/HistoryBackButton'
import PageHeader from '../components/shared/PageHeader'

const effectiveDate = 'August 4, 2026'

const sections = [
  {
    title: 'Using TailorDeck',
    body: [
      'TailorDeck helps tailors and fashion designers manage shop records, clients, measurements, jobs, deadlines, expenses, invoices, receipts, and subscriptions.',
      'You must provide accurate account information and keep your login details secure.',
      'You are responsible for all activity that happens under your account unless caused by TailorDeck’s own system failure or unauthorized breach.',
    ],
  },
  {
    title: 'Client Records and Consent',
    body: [
      'You are responsible for getting permission before storing client names, phone numbers, measurements, reference photos, job details, or related records in TailorDeck.',
      'You must not upload unlawful, harmful, private, misleading, abusive, copyrighted, or unrelated content.',
      'TailorDeck is a business management tool and does not replace your professional judgment, agreement with clients, or business record obligations.',
    ],
  },
  {
    title: 'Accounts and Security',
    body: [
      'You must use a valid email address and may be required to verify your email before using the full service.',
      'You should notify us if you suspect unauthorized access to your account.',
      'We may restrict, suspend, or terminate accounts that abuse the service, violate these terms, attempt to bypass security, or harm other users.',
    ],
  },
  {
    title: 'Plans, Trials, and Payment',
    body: [
      'TailorDeck may offer free trials, starter plans, pro plans, beta tester access, discounts, or other subscription options.',
      'Paid plans are processed through Paystack or another approved payment provider. TailorDeck does not directly store your card or bank payment details.',
      'If a trial ends and no active paid plan is available, some features may be limited until you upgrade.',
      'Plan features, pricing, and trial rules may change as the product grows, but active users will be notified where appropriate.',
    ],
  },
  {
    title: 'Refunds and Cancellations',
    body: [
      'You may cancel or change your plan through the app where supported.',
      'Cancellation may stop future renewals but may not automatically refund past payments unless required by law or stated in a specific offer.',
      'Refund requests will be reviewed based on payment status, service usage, billing errors, and applicable payment provider rules.',
    ],
  },
  {
    title: 'Documents and WhatsApp Sharing',
    body: [
      'Invoices, receipts, PDFs, and WhatsApp messages generated by TailorDeck are based on the information you enter.',
      'You are responsible for checking document accuracy before sending it to a client.',
      'When you share through WhatsApp or another platform, that platform’s terms and privacy practices also apply.',
    ],
  },
  {
    title: 'Availability and Changes',
    body: [
      'We aim to keep TailorDeck reliable, but we do not guarantee uninterrupted service at all times.',
      'Features may be improved, removed, renamed, restricted, or added as TailorDeck develops.',
      'During beta or early production, some features may change quickly based on testing, security, payment, or user feedback.',
    ],
  },
  {
    title: 'Intellectual Property',
    body: [
      'TailorDeck, its design, logo, software, workflows, and product materials belong to TailorDeck, BBW Tech-Innovation, or their licensors.',
      'You keep ownership of your business data, client records, uploaded files, and job information, subject to the permissions needed for TailorDeck to provide the service.',
    ],
  },
  {
    title: 'Limitation of Liability',
    body: [
      'TailorDeck is provided as a business management tool. We are not responsible for losses caused by inaccurate user-entered data, missed client agreements, offline issues, device problems, third-party downtime, or unauthorized use caused by weak account security.',
      'To the fullest extent allowed by law, TailorDeck will not be liable for indirect, incidental, special, or consequential losses.',
    ],
  },
  {
    title: 'Termination',
    body: [
      'You may stop using TailorDeck or request account deletion.',
      'We may suspend or terminate access if these terms are violated, payment fails, abuse is detected, or continued access creates legal, security, or operational risk.',
    ],
  },
  {
    title: 'Contact',
    body: [
      'For questions about these terms, billing, support, or account deletion, contact support@tailordeck.com.ng. If this address is not yet active during beta, use the support channel provided inside the app.',
    ],
  },
]

export default function TermsOfService() {
  return (
    <main className="legal-page">
      <section className="legal-shell">
        <PageHeader title="Terms of Service" centered leading={<HistoryBackButton fallbackTo="/onboarding" />} />

        <section className="legal-hero">
          <div className="legal-brand">
            <span className="app-shell-logo-wrap" aria-hidden>
              <img src="/branding/TailorDeck%20app%20logo%20for%20splac%20screen.png" alt="" className="app-shell-logo" />
            </span>
            <span>TailorDeck</span>
          </div>
          <p>Effective date: {effectiveDate}</p>
          <p>
            These Terms of Service explain the rules for using TailorDeck. By creating an account or using the app, you agree to these terms.
          </p>
        </section>

        <div className="legal-section-list">
          {sections.map((section) => (
            <section key={section.title} className="legal-section">
              <h2>{section.title}</h2>
              {section.body.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </section>
          ))}
        </div>

        <section className="legal-note">
          <p>
            These terms may be updated as TailorDeck grows. Continued use after updates means you accept the latest terms.
          </p>
        </section>

        <div className="legal-actions">
          <Link to="/privacy-policy" className="btn btn-secondary btn-full">Read Privacy Policy</Link>
          <Link to="/onboarding" className="btn btn-primary btn-full">Back to TailorDeck</Link>
        </div>
      </section>
    </main>
  )
}
