export type MaterialColorOption = {
  name: string
  hex: string
}

export type MaterialColorCategory = {
  id: string
  title: string
  options: MaterialColorOption[]
}

export const commonMaterialColors: MaterialColorOption[] = [
  { name: 'Black', hex: '#111111' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Navy Blue', hex: '#1B2A4A' },
  { name: 'Wine', hex: '#7B1E37' },
  { name: 'Gold', hex: '#C9A84C' },
  { name: 'Cream', hex: '#F4E8D5' },
]

export const materialColorCategories: MaterialColorCategory[] = [
  {
    id: 'neutral',
    title: 'Neutral Colors',
    options: [
      { name: 'Black', hex: '#111111' },
      { name: 'Charcoal', hex: '#2D2D2D' },
      { name: 'Graphite', hex: '#3F3F46' },
      { name: 'Slate', hex: '#475569' },
      { name: 'Ash', hex: '#9CA3AF' },
      { name: 'Grey', hex: '#8C8C8C' },
      { name: 'Silver', hex: '#C0C0C0' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Ivory', hex: '#FFFFF0' },
      { name: 'Cream', hex: '#F4E8D5' },
      { name: 'Beige', hex: '#D8C3A5' },
      { name: 'Taupe', hex: '#8B7E74' },
      { name: 'Sand', hex: '#C2B280' },
      { name: 'Stone', hex: '#A8A29E' },
      { name: 'Chocolate', hex: '#4E342E' },
      { name: 'Brown', hex: '#6B3F2A' },
      { name: 'Tan', hex: '#D2B48C' },
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Coffee', hex: '#6F4E37' },
      { name: 'Mocha', hex: '#967969' },
      { name: 'Khaki', hex: '#BDB76B' },
      { name: 'Olive Grey', hex: '#6B705C' },
      { name: 'Oat', hex: '#DDD6C2' },
      { name: 'Bone', hex: '#E3DAC9' },
    ],
  },
  {
    id: 'warm',
    title: 'Warm Colors',
    options: [
      { name: 'Red', hex: '#C62828' },
      { name: 'Scarlet', hex: '#FF2400' },
      { name: 'Ruby', hex: '#9B111E' },
      { name: 'Burgundy', hex: '#800020' },
      { name: 'Wine', hex: '#7B1E37' },
      { name: 'Maroon', hex: '#800000' },
      { name: 'Rose', hex: '#E11D48' },
      { name: 'Coral', hex: '#FF7F50' },
      { name: 'Orange', hex: '#F97316' },
      { name: 'Burnt Orange', hex: '#CC5500' },
      { name: 'Rust', hex: '#B7410E' },
      { name: 'Copper', hex: '#B87333' },
      { name: 'Bronze', hex: '#CD7F32' },
      { name: 'Gold', hex: '#C9A84C' },
      { name: 'Mustard', hex: '#D4A017' },
      { name: 'Yellow', hex: '#FACC15' },
      { name: 'Lemon', hex: '#FFF44F' },
      { name: 'Amber', hex: '#F59E0B' },
      { name: 'Peach', hex: '#FDBA74' },
      { name: 'Apricot', hex: '#FBCEB1' },
      { name: 'Blush', hex: '#F2B8B5' },
      { name: 'Terracotta', hex: '#E2725B' },
      { name: 'Brick', hex: '#B22222' },
      { name: 'Tomato', hex: '#FF6347' },
    ],
  },
  {
    id: 'cool',
    title: 'Cool Colors',
    options: [
      { name: 'Navy Blue', hex: '#1B2A4A' },
      { name: 'Royal Blue', hex: '#2563EB' },
      { name: 'Sky Blue', hex: '#93C5FD' },
      { name: 'Powder Blue', hex: '#B0E0E6' },
      { name: 'Baby Blue', hex: '#89CFF0' },
      { name: 'Teal', hex: '#0F766E' },
      { name: 'Turquoise', hex: '#40E0D0' },
      { name: 'Aqua', hex: '#00FFFF' },
      { name: 'Cyan', hex: '#06B6D4' },
      { name: 'Mint', hex: '#A7F3D0' },
      { name: 'Emerald', hex: '#047857' },
      { name: 'Green', hex: '#118C5A' },
      { name: 'Forest Green', hex: '#228B22' },
      { name: 'Olive', hex: '#808000' },
      { name: 'Sage', hex: '#9CAF88' },
      { name: 'Lime', hex: '#84CC16' },
      { name: 'Purple', hex: '#7C3AED' },
      { name: 'Violet', hex: '#8B5CF6' },
      { name: 'Indigo', hex: '#4F46E5' },
      { name: 'Lavender', hex: '#B57EDC' },
      { name: 'Lilac', hex: '#C4B5FD' },
      { name: 'Plum', hex: '#673147' },
      { name: 'Mauve', hex: '#E0B0FF' },
      { name: 'Periwinkle', hex: '#CCCCFF' },
    ],
  },
  {
    id: 'soft',
    title: 'Soft Colors',
    options: [
      { name: 'Pink', hex: '#F9A8D4' },
      { name: 'Hot Pink', hex: '#FF69B4' },
      { name: 'Fuchsia', hex: '#D946EF' },
      { name: 'Magenta', hex: '#FF00FF' },
      { name: 'Dusty Rose', hex: '#C9A9A6' },
      { name: 'Champagne', hex: '#F7E7CE' },
      { name: 'Pearl', hex: '#F8F6F0' },
      { name: 'Vanilla', hex: '#F3E5AB' },
      { name: 'Butter', hex: '#FFF1A8' },
      { name: 'Pastel Yellow', hex: '#FDFD96' },
      { name: 'Pastel Green', hex: '#77DD77' },
      { name: 'Pastel Blue', hex: '#AEC6CF' },
      { name: 'Pastel Purple', hex: '#C3B1E1' },
      { name: 'Pastel Pink', hex: '#FFD1DC' },
      { name: 'Seafoam', hex: '#9FE2BF' },
      { name: 'Ice Blue', hex: '#D6F3FF' },
      { name: 'Pistachio', hex: '#93C572' },
      { name: 'Honey', hex: '#FFC30B' },
      { name: 'Caramel', hex: '#AF6E4D' },
      { name: 'Cocoa', hex: '#7B3F00' },
      { name: 'Almond', hex: '#EED9C4' },
      { name: 'Nude', hex: '#E3BC9A' },
      { name: 'Salmon', hex: '#FA8072' },
      { name: 'Orchid', hex: '#DA70D6' },
    ],
  },
  {
    id: 'metallic',
    title: 'Metallic Colors',
    options: [
      { name: 'Metallic Gold', hex: '#D4AF37' },
      { name: 'Rose Gold', hex: '#B76E79' },
      { name: 'Metallic Silver', hex: '#C9C9C9' },
      { name: 'Gunmetal', hex: '#2A3439' },
      { name: 'Steel Blue', hex: '#4682B4' },
      { name: 'Pewter', hex: '#899499' },
      { name: 'Antique Gold', hex: '#CFB53B' },
      { name: 'Brass', hex: '#B5A642' },
      { name: 'Chrome', hex: '#D7D7D7' },
      { name: 'Platinum', hex: '#E5E4E2' },
      { name: 'Champagne Gold', hex: '#F1DDCF' },
      { name: 'Copper Rose', hex: '#996666' },
    ],
  },
]
