import type { NewJobWizardStateModel } from './useNewJobWizardState'

export function getNewJobWizardStateSnapshot(state: NewJobWizardStateModel) {
  return {
    amendmentArea: state.amendmentArea,
    amendmentDescription: state.amendmentDescription,
    amendmentIssueType: state.amendmentIssueType,
    amendmentNeedsMaterials: state.amendmentNeedsMaterials,
    amendmentPartName: state.amendmentPartName,
    amendmentPartQuantity: state.amendmentPartQuantity,
    amendmentTarget: state.amendmentTarget,
    chargeAmount: state.chargeAmount,
    clientName: state.clientName,
    clientPhone: state.clientPhone,
    createdJobId: state.createdJobId,
    customMaterialType: state.customMaterialType,
    deadlineDate: state.deadlineDate,
    deadlineTime: state.deadlineTime,
    depositPercent: state.depositPercent,
    draftSaved: state.draftSaved,
    expenseDraftCost: state.expenseDraftCost,
    expenseDraftName: state.expenseDraftName,
    expenses: state.expenses,
    fieldErrorKey: state.fieldErrorKey,
    fieldErrors: state.fieldErrors,
    isFinalizing: state.isFinalizing,
    isSavingDraft: state.isSavingDraft,
    itemType: state.itemType,
    jobType: state.jobType,
    makeCategory: state.makeCategory,
    materialColor: state.materialColor,
    materialQuality: state.materialQuality,
    materialSource: state.materialSource,
    materialType: state.materialType,
    materialYards: state.materialYards,
    nonBodyDescription: state.nonBodyDescription,
    nonBodyMeasurements: state.nonBodyMeasurements,
    nonBodyQuantity: state.nonBodyQuantity,
    openMaterialCategory: state.openMaterialCategory,
    orderMode: state.orderMode,
    persons: state.persons,
    referencePhotoFiles: state.referencePhotoFiles,
    referencePhotoFilesByTarget: state.referencePhotoFilesByTarget,
    referencePhotoNames: state.referencePhotoNames,
    referencePhotoNamesByTarget: state.referencePhotoNamesByTarget,
    reminder: state.reminder,
    sameItemForAll: state.sameItemForAll,
    singleMeasurementsOpen: state.singleMeasurementsOpen,
    step: state.step,
    stepFourDetailsOpen: state.stepFourDetailsOpen,
    stepFourReviewMode: state.stepFourReviewMode,
    stepOneMeasurementsOpen: state.stepOneMeasurementsOpen,
    successOpen: state.successOpen,
    worthIt: state.worthIt,
  }
}
