// Local staging: a full Supabase (database, auth, storage, functions) running in Docker on this computer,
// built from supabase/migrations, with test accounts only. It never connects to production.
//
//   npm run staging:start   start it (first run downloads images) and prepare the test account
//   npm run staging:reset   wipe it and rebuild from the migrations (use this to test a new migration)
//   npm run staging:stop    stop it (data is kept until the next reset)
//   npm run dev:staging     the app on http://localhost:5173 using staging
//   npm run test:e2e:staging  the end-to-end tests against staging
//   npm run test:db:staging   the SQL permission tests in supabase/tests
//
// Emails (sign-up codes, password reset) are not sent; they appear in Mailpit (URL printed below).

import { spawnSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createClient } from '@supabase/supabase-js'

const ENV_FILE = '.env.staging'
// Local-only test account. These values exist only in the Docker database on this computer.
const QA_EMAIL = 'qa@staging.local'
const QA_PASSWORD = 'staging-qa-password-1'

function run(command, env = process.env) {
  const result = spawnSync(command, { stdio: 'inherit', shell: true, env })
  if (result.status !== 0) process.exit(result.status ?? 1)
}

function localStatus() {
  const result = spawnSync('npx supabase status -o env', { shell: true, encoding: 'utf8' })
  if (result.status !== 0) {
    console.error('Local Supabase is not running. Start Docker Desktop, then run: npm run staging:start')
    process.exit(1)
  }
  const values = {}
  for (const line of result.stdout.split(/\r?\n/)) {
    const match = line.match(/^([A-Z_]+)="?(.*?)"?$/)
    if (match) values[match[1]] = match[2]
  }
  return values
}

/** Refuses anything that is not this computer, so a wrong setting can never touch production. */
function assertLocal(url) {
  const host = url ? new URL(url).hostname : ''
  if (host !== '127.0.0.1' && host !== 'localhost') {
    console.error(`Refusing to continue: staging must run on this computer, got "${url}".`)
    process.exit(1)
  }
}

// Local Edge Function settings (git-ignored). Test values only; real secrets live in Supabase, never here.
function writeLocalFunctionEnv() {
  const file = 'supabase/functions/.env'
  if (existsSync(file)) return false
  writeFileSync(file, '# Local staging only (written by scripts/staging.mjs)\nACCOUNT_CLEANUP_SECRET=local-staging-cleanup-secret\n')
  return true
}

async function prepare() {
  const status = localStatus()
  assertLocal(status.API_URL)

  const admin = createClient(status.API_URL, status.SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } })
  const { data: list, error: listError } = await admin.auth.admin.listUsers()
  if (listError) throw listError
  let user = list.users.find((candidate) => candidate.email === QA_EMAIL)
  if (!user) {
    const { data, error } = await admin.auth.admin.createUser({ email: QA_EMAIL, password: QA_PASSWORD, email_confirm: true })
    if (error) throw error
    user = data.user
  }
  // The test account is also a support and website admin, so /admin can be tried locally.
  const { error: adminError } = await admin.from('admin_users').upsert({ user_id: user.id, roles: ['support', 'website'] })
  if (adminError) throw adminError

  writeFileSync(
    ENV_FILE,
    [
      '# Generated by scripts/staging.mjs for local staging (Docker on this computer). Safe local defaults only.',
      `VITE_SUPABASE_URL=${status.API_URL}`,
      `VITE_SUPABASE_ANON_KEY=${status.ANON_KEY}`,
      'VITE_ALLOW_WEB_APP=true',
      '# Keep local test errors out of the production Sentry project.',
      'VITE_SENTRY_DSN=',
      `E2E_TEST_EMAIL=${QA_EMAIL}`,
      `E2E_TEST_PASSWORD=${QA_PASSWORD}`,
      `E2E_MAILPIT_URL=${status.MAILPIT_URL}`,
      '',
    ].join('\n'),
  )

  console.log('\nStaging is ready (this computer only).')
  console.log(`  App:            npm run dev:staging, then http://localhost:5173`)
  console.log(`  Test login:     ${QA_EMAIL} / ${QA_PASSWORD} (also an admin)`)
  console.log(`  Database admin: ${status.STUDIO_URL}`)
  console.log(`  Emails:         ${status.MAILPIT_URL}`)
}

const command = process.argv[2]
if (command === 'start') {
  writeLocalFunctionEnv()
  run('npx supabase start')
  await prepare()
} else if (command === 'reset') {
  localStatus()
  run('npx supabase db reset --local')
  await prepare()
} else if (command === 'stop') {
  run('npx supabase stop')
} else if (command === 'db-test') {
  // SQL permission tests in supabase/tests (each runs in a transaction that is rolled back).
  assertLocal(localStatus().API_URL)
  for (const file of readdirSync('supabase/tests').filter((name) => name.endsWith('.sql')).sort()) {
    console.log(`\n${file}`)
    const result = spawnSync('docker', ['exec', '-i', 'supabase_db_tailordeck', 'psql', '-q', '-U', 'postgres', '-d', 'postgres'], {
      input: readFileSync(join('supabase/tests', file), 'utf8'),
      encoding: 'utf8',
    })
    const output = `${result.stdout}${result.stderr}`
    for (const line of output.split(/\r?\n/)) if (/NOTICE:\s+ok:|passed|ERROR|FAIL/.test(line)) console.log(`  ${line.replace(/^NOTICE:\s+/, '')}`)
    if (result.status !== 0 || /ERROR|FAIL/.test(output)) process.exit(1)
  }
} else if (command === 'e2e') {
  assertLocal(localStatus().API_URL)
  // The admin two-step test sets up an authenticator on the QA account; start every run without one.
  spawnSync('docker', ['exec', 'supabase_db_tailordeck', 'psql', '-U', 'postgres', '-c',
    `delete from auth.mfa_factors where user_id = (select id from auth.users where email = '${QA_EMAIL}')`], { stdio: 'ignore' })
  run('npm run build -- --mode staging')
  // Fewer parallel browsers: the whole Supabase stack is running on the same computer.
  run(`npx playwright test --workers=2 ${process.argv.slice(3).join(' ')}`, { ...process.env, E2E_ENV_FILE: ENV_FILE })
} else {
  console.error('Usage: node scripts/staging.mjs <start|reset|stop|e2e|db-test>')
  process.exit(1)
}
