-- Follow-up to 20261006120000: NOT NULL job columns fall back to their table defaults when the payload
-- omits them (found by a rolled-back test: a missing amendment_needs_materials failed the insert).
create or replace function public.save_full_job(
  p_job_id uuid,
  p_job jsonb,
  p_persons jsonb default '[]'::jsonb,
  p_expenses jsonb default '[]'::jsonb,
  p_new_client jsonb default null
)
returns public.jobs
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
  lagos_today date := (now() at time zone 'Africa/Lagos')::date;
  saved_job public.jobs;
  job_client_id uuid := nullif(p_job ->> 'client_id', '')::uuid;
begin
  if current_user_id is null then
    raise exception 'Authentication required.' using errcode = '28000';
  end if;

  -- New client typed into the wizard (id generated by the app, so a retry does not create a second one).
  if p_new_client is not null then
    job_client_id := (p_new_client ->> 'id')::uuid;
    insert into public.clients (id, user_id, name, phone, phone_normalized, sex, measurement_unit, last_job_date)
    select job_client_id, current_user_id, c.name, c.phone, c.phone_normalized, c.sex,
           coalesce(c.measurement_unit, 'inches'), lagos_today
    from jsonb_populate_record(null::public.clients, p_new_client) c
    on conflict (id) do nothing;
  end if;

  if exists (select 1 from public.jobs where id = p_job_id and user_id = current_user_id) then
    update public.jobs j
    set client_id = job_client_id,
        client_name = r.client_name,
        client_phone = r.client_phone,
        client_phone_normalized = r.client_phone_normalized,
        title = r.title,
        order_mode = coalesce(r.order_mode, 'New Stitch'),
        make_category = coalesce(r.make_category, 'Body Wear'),
        order_scope = coalesce(r.order_scope, 'Single'),
        item_type = r.item_type,
        description = r.description,
        charge_amount_kobo = coalesce(r.charge_amount_kobo, 0),
        deposit_percent = coalesce(r.deposit_percent, 0),
        deposit_amount_kobo = coalesce(r.deposit_amount_kobo, 0),
        deadline_date = r.deadline_date,
        deadline_time = r.deadline_time,
        reminder = coalesce(r.reminder, '1 day before'),
        custom_reminder_value = r.custom_reminder_value,
        custom_reminder_unit = r.custom_reminder_unit,
        custom_reminder_minutes = r.custom_reminder_minutes,
        reminder_label = r.reminder_label,
        status = coalesce(r.status, 'draft'),
        same_item_for_all = coalesce(r.same_item_for_all, true),
        amendment_issue_type = r.amendment_issue_type,
        amendment_area = r.amendment_area,
        amendment_target = r.amendment_target,
        amendment_description = r.amendment_description,
        amendment_needs_materials = coalesce(r.amendment_needs_materials, false),
        amendment_part_name = r.amendment_part_name,
        amendment_part_quantity = r.amendment_part_quantity,
        material_type = r.material_type,
        material_color = r.material_color,
        material_yards = r.material_yards,
        material_quality = r.material_quality,
        material_source = r.material_source,
        total_expenses_kobo = coalesce(r.total_expenses_kobo, 0),
        is_worth_it = r.is_worth_it
    from jsonb_populate_record(null::public.jobs, p_job) r
    where j.id = p_job_id and j.user_id = current_user_id;
  else
    insert into public.jobs (
      id, user_id, client_id, client_name, client_phone, client_phone_normalized, title, order_mode, make_category,
      order_scope, item_type, description, charge_amount_kobo, deposit_percent, deposit_amount_kobo, deadline_date,
      deadline_time, reminder, custom_reminder_value, custom_reminder_unit, custom_reminder_minutes, reminder_label,
      status, same_item_for_all, amendment_issue_type, amendment_area, amendment_target, amendment_description,
      amendment_needs_materials, amendment_part_name, amendment_part_quantity, material_type, material_color,
      material_yards, material_quality, material_source, total_expenses_kobo, is_worth_it
    )
    select
      p_job_id, current_user_id, job_client_id, r.client_name, r.client_phone, r.client_phone_normalized, r.title,
      coalesce(r.order_mode, 'New Stitch'), coalesce(r.make_category, 'Body Wear'), coalesce(r.order_scope, 'Single'), r.item_type, r.description, coalesce(r.charge_amount_kobo, 0), coalesce(r.deposit_percent, 0),
      coalesce(r.deposit_amount_kobo, 0), r.deadline_date, r.deadline_time, coalesce(r.reminder, '1 day before'), r.custom_reminder_value,
      r.custom_reminder_unit, r.custom_reminder_minutes, r.reminder_label, coalesce(r.status, 'draft'), coalesce(r.same_item_for_all, true),
      r.amendment_issue_type, r.amendment_area, r.amendment_target, r.amendment_description,
      coalesce(r.amendment_needs_materials, false), r.amendment_part_name, r.amendment_part_quantity, r.material_type,
      r.material_color, r.material_yards, r.material_quality, r.material_source, coalesce(r.total_expenses_kobo, 0), r.is_worth_it
    from jsonb_populate_record(null::public.jobs, p_job) r;
  end if;

  -- Persons/measurements and expenses: replaced inside the same transaction, so they can never be lost.
  delete from public.job_persons where job_id = p_job_id and user_id = current_user_id;
  insert into public.job_persons (
    job_id, user_id, client_id, name, person_name, sex, role, age, item_type, description, is_primary,
    measurement_kind, quantity, measurements, measurement_unit, sort_order
  )
  select
    p_job_id, current_user_id, job_client_id, p.name, p.person_name, p.sex, coalesce(p.role, 'adult'), p.age,
    p.item_type, p.description, coalesce(p.is_primary, false), coalesce(p.measurement_kind, 'body'),
    coalesce(p.quantity, 1), coalesce(p.measurements, '{}'::jsonb), coalesce(p.measurement_unit, 'inches'),
    coalesce(p.sort_order, 0)
  from jsonb_populate_recordset(null::public.job_persons, coalesce(p_persons, '[]'::jsonb)) p;

  delete from public.job_expenses where job_id = p_job_id and user_id = current_user_id;
  insert into public.job_expenses (job_id, user_id, name, cost_amount_kobo)
  select p_job_id, current_user_id, e.name, coalesce(e.cost_amount_kobo, 0)
  from jsonb_populate_recordset(null::public.job_expenses, coalesce(p_expenses, '[]'::jsonb)) e;

  if job_client_id is not null and coalesce(p_job ->> 'status', 'draft') <> 'draft' then
    update public.clients
    set last_job_date = lagos_today, updated_at = now()
    where id = job_client_id and user_id = current_user_id;
  end if;

  select * into saved_job from public.jobs where id = p_job_id and user_id = current_user_id;
  return saved_job;
end;
$$;

revoke all on function public.save_full_job(uuid, jsonb, jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.save_full_job(uuid, jsonb, jsonb, jsonb, jsonb) to authenticated;
